INSERT
	INTO
	channel_mapping
	(
	network_name_pattern, 
	platform, 
	fb_install_referrer_publisher_platform_pattern,
	medium_name_pattern,
	campaign_name_pattern,
	adgroup_name_pattern, 
	first_referer,
	channel_detail,
	channel
	)
VALUES
('apple search ads','mobile',null,null,null,null,null,'Apple Search Ads','Apple Search'),
('awin - qr code','mobile',null,null,null,null,null,'Awin','Affiliate'),
('awin - smartbanner','mobile',null,null,null,null,null,'Awin','Affiliate'),
('awin - web signup','mobile',null,null,null,null,null,'Awin','Affiliate'),
('braze - canvas','mobile',null,null,null,null,null,'Braze','CRM'),
('braze - email','mobile',null,null,null,null,null,'Braze','CRM'),
('braze - push','mobile',null,null,null,null,null,'Braze','CRM'),
('braze - smartbanner','mobile',null,null,null,null,null,'Braze','CRM'),
('braze - web signup','mobile',null,null,null,null,null,'Braze','CRM'),
('braze - website','mobile',null,null,null,null,null,'Braze','CRM'),
('facebook ads','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('facebook ads - landing page','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('facebook ads - smartbanner','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('facebook ads - web signup','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('facebook ads - website','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('facebook ads - dynamic lp test - app download button','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('facebook ads - static lp test - app download button','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('facebook organic - web signup','mobile',null,null,null,null,null,'Meta Organic','Organic Social'),
('facebook organic','mobile',null,null,null,null,null,'Meta Organic','Organic Social'),
('friend referral','mobile',null,null,null,null,null,'Referral','Referral'),
('google ads (unknown)','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads - qr code','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads - qr code','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads - smartbanner','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads - web signup','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads - website','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads - dynamic lp test - app download button','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads - dynamic lp test - qr code','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google ads ace','mobile',null,null,null,null,null,'Google Ads ACE','Retargeting'),
('google ads aci','mobile',null,null,null,null,null,'Google UAC','UAC'),
('google ads performance max','mobile',null,null,null,null,null,'Google Ads Performance Max','Display'),
('google ads performance max - qr code','mobile',null,null,null,null,null,'Google Ads Performance Max','Display'),
('google ads performance max - smartbanner','mobile',null,null,null,null,null,'Google Ads Performance Max','Display'),
('google ads performance max - web signup','mobile',null,null,null,null,null,'Google Ads Performance Max','Display'),
('google ads performance max - website','mobile',null,null,null,null,null,'Google Ads Performance Max','Display'),
('google ads search','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google organic  search','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic  search - qr code','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic  search - smartbanner','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic  search - web signup','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic  search - website','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic search','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic search - qr code','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic search - smartbanner','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic search - web signup','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google organic search - website','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('google search ads - qr code','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google search ads - qr code','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google search ads - smartbanner','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google search ads - web signup','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('google search ads - website','mobile',null,null,null,null,null,'Google Search','Paid Search'),
('growth testing','mobile',null,null,null,null,null,'Growth Testing','Misc. testing'),
('heyjobs','mobile',null,null,null,null,null,'Heyjobs','Job Boards'),
('indeed ads - mobile signup - app download button','mobile',null,null,null,null,null,'Indeed','Job Boards'),
('indeed ads - website - app download button','mobile',null,null,null,null,null,'Indeed','Job Boards'),
('instagram','mobile',null,null,null,null,null,'Meta Paid','Organic Social'),
('instagram organic','mobile',null,null,null,null,null,'Instagram Organic','Organic Social'),
('instagram organic - link tree','mobile',null,null,null,null,null,'Instagram Organic','Organic Social'),
('instagram organic - smartbanner','mobile',null,null,null,null,null,'Instagram Organic','Organic Social'),
('instagram organic - stories','mobile',null,null,null,null,null,'Instagram Organic','Organic Social'),
('instagram organic - web signup','mobile',null,null,null,null,null,'Instagram Organic','Organic Social'),
('instagram organic - website','mobile',null,null,null,null,null,'Instagram Organic','Organic Social'),
('instagram stories','mobile',null,null,null,null,null,'Instagram Organic','Organic Social'),
('jobsora ads','mobile',null,null,null,null,null,'Jobsora','Job Boards'),
('jobsora ads - smartbanner','mobile',null,null,null,null,null,'Jobsora','Job Boards'),
('jobsora ads - web signup','mobile',null,null,null,null,null,'Jobsora','Job Boards'),
('jobsora ads - website','mobile',null,null,null,null,null,'Jobsora','Job Boards'),
('meta paid - smartbanner','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('meta paid - web signup','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('meta paid - website','mobile',null,null,null,null,null,'Meta Paid','Paid Social'),
('misc. organic search','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('misc. organic search - qr code','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('misc. organic search - smartbanner','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('misc. organic search - web signup','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('misc. organic search - website','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('misc. traffic - qr code','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('misc. traffic - smartbanner','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('misc. traffic - web signup','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('misc. traffic - website','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('misc. traffic - website','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('offline','mobile',null,null,null,null,null,'Offline','Offline'),
('organic','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('organic - app store','mobile',null,null,null,null,null,'Organic','Organic'),
('organic search','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('organic search -  qr code','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('organic search - qr code','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('organic search - smartbanner','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('organic search - web signup','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('organic search - website','mobile',null,null,null,null,null,'Misc. Organic Search','Organic Search'),
('organic search','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('organic search -  qr code','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('organic search - qr code','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('organic search - smartbanner','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('organic search - web signup','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('organic search - website','mobile',null,null,null,'google',null,'Google Organic Search','Organic Search'),
('organic social - website - app download button','mobile',null,null,null,null,null,'Organic','Organic'),
('referral','mobile',null,null,null,null,null,'Referral','Referral'),
('stepstone','mobile',null,null,null,null,null,'Stepstone','Job Boards'),
('stepstone ads - qr code','mobile',null,null,null,null,null,'Stepstone','Job Boards'),
('stepstone ads - smartbanner','mobile',null,null,null,null,null,'Stepstone','Job Boards'),
('stepstone ads - web signup','mobile',null,null,null,null,null,'Stepstone','Job Boards'),
('stepstone ads - website','mobile',null,null,null,null,null,'Stepstone','Job Boards'),
('tiktok','mobile',null,null,null,null,null,'Tiktok Paid','Paid Social'),
('tiktok san','mobile',null,null,null,null,null,'Tiktok Paid','Paid Social'),
('tiktok ads','mobile',null,null,null,null,null,'Tiktok Paid','Paid Social'),
('tiktok ads - direct link','mobile',null,null,null,null,null,'Tiktok Paid','Paid Social'),
('tiktok ads - influencer','mobile',null,null,null,null,null,'Tiktok Paid','Paid Social'),
('tiktok installs','mobile',null,null,null,null,null,'Tiktok Paid','Paid Social'),
('tiktok organic','mobile',null,null,null,null,null,'Tiktok Organic','Organic Social'),
('tiktok organic - link tree','mobile',null,null,null,null,null,'Tiktok Organic','Organic Social'),
('tiktok organic - smartbanner','mobile',null,null,null,null,null,'Tiktok Organic','Organic Social'),
('tiktok organic - web signup','mobile',null,null,null,null,null,'Tiktok Organic','Organic Social'),
('unattributed','mobile','audience_network',null,null,null,null,'Meta Paid','Paid Social'),
('unattributed','mobile','facebook',null,null,null,null,'Meta Paid','Paid Social'),
('unattributed','mobile','instagram',null,null,null,null,'Instagram Paid','Paid Social'),
('unknown - qr code','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('unknown - smartbanner','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('unknown - web signup','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('unknown - website','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('website clickout','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('website clickout - qr code','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('website clickout - smartbanner','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('website clickout - web signup','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('website clickout - website','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('website_app_download_test','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('nan','mobile',null,null,null,null,null,'Unknown/organic','Unknown/organic'),
('awin','web',null,null,null,null,null,'Awin','Affliate'),
('braze','web',null,null,null,null,null,'Braze','CRM'),
('facebook','web',null,null,null,null,null,'Meta Organic','Organic Social'),
('google-search','web',null,null,'pmax',null,null,'Google Ads Performance Max','Display'),
('google-search','web',null,null,'sem',null,null,'Google Search','Paid Search'),
('google_jobs_apply','web',null,null,null,null,null,'Google Organic Search','Organic Search'),
('heyjobs','web',null,null,null,null,null,'Heyjobs','Job Boards'),
('instagram','web',null,'organic',null,null,null,'Instagram Organic','Organic Social'),
('jobsora','web',null,null,null,null,null,'Jobsora','Job Boards'),
('localpromo','web',null,null,null,null,null,'Offline','Offline'),
('meta','web',null,'organic',null,null,null,'Meta Organic','Organic Social'),
('meta','web',null,'cpm',null,null,null,'Meta Paid','Paid Social'),
('stepstone','web',null,null,null,null,null,'Stepstone','Job Boards'),
('tiktok','web',null,'cpm',null,null,null,'Tiktok Paid','Paid Social'),
('tiktok','web',null,'organic',null,null,null,'Tiktok Organic','Organic Social'),
('website','web',null,null,null,null,null,'Referral','Referral'),
(null,'web',null,null,null,null,'ecosia','Misc. Organic Search','Organic Search'),
(null,'web',null,null,null,null,'google','Google Organic Search','Organic Search'),
(null,'web',null,null,null,null,'bing','Misc. Organic Search','Organic Search'),
(null,'web',null,null,null,null,'tiktok','Tiktok Organic','Organic Social')